# Generated by Django 2.0 on 2019-02-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='image',
        ),
    ]
