# Generated by Django 2.1.5 on 2019-02-25 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50)),
                ('bills', models.CharField(max_length=50)),
                ('order_number', models.PositiveIntegerField()),
                ('bill_date', models.DateField(default=datetime.date.today, verbose_name='Bill Date')),
                ('due_date', models.DateField(default=datetime.date.today, verbose_name='Due Date')),
                ('payment_terms', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50)),
                ('purchase_order_number', models.PositiveIntegerField()),
                ('reference_number', models.PositiveIntegerField()),
                ('date', models.DateField(verbose_name='Date')),
                ('delivery_date', models.DateField(verbose_name='Delivery Date')),
                ('shipment_preference', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=120)),
            ],
        ),
    ]
