# Generated by Django 2.1.5 on 2019-02-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='hsn_sac',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_name',
            field=models.CharField(max_length=50),
        ),
    ]
