# Generated by Django 2.1.5 on 2019-02-25 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bill_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50)),
                ('profile_name', models.CharField(max_length=50)),
                ('repeat_every', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=120)),
                ('start', models.DateField(default=datetime.date.today, verbose_name='Start on')),
                ('end', models.DateField(default=datetime.date.today, verbose_name='Ends on')),
                ('payment_terms', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=120)),
            ],
        ),
    ]
