# Generated by Django 2.1.5 on 2019-02-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190214_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='profile_pic',
            field=models.ImageField(default='media_data/profile-pic.png', upload_to='media_data'),
        ),
    ]
