# Generated by Django 2.1.5 on 2019-02-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190214_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='profile_pic',
            field=models.ImageField(upload_to='media_data'),
        ),
    ]
