# Generated by Django 2.1.5 on 2019-02-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_items_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='profile_pic',
            field=models.ImageField(default='/profile-pic.png', upload_to='media_data'),
        ),
    ]
